### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by kr** [qcmaude/cap#1]
- [ ] record blobs
- [ ] record commits (pointing to one blob and one parent commit)
- [ ] one ref (default branch)
- [ ] `commit` command (records blob, records commit, updates ref)
- [ ] `fetch` command (copies objects & remote refs)
- [ ] `merge --ff-only` command (updates ref)

**Comment by kr** [comment]
Notes:

- using json
- hash of external representation (as stored on disk) is object hash
- using blake2 as hash function
